#ifndef CARDDISPLAY_H
#define CARDDISPLAY_H
#include <string>

/*

const string card1 =   " _________ \n"
                        "|A        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________A|\n";
const string card2 =   " _________ \n"
                        "|2        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________2|\n";
const string card3 =   " _________ \n"
                        "|3        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________3|\n";
const string card4 =   " _________ \n"
                        "|4        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________4|\n";
const string card5 =   " _________ \n"
                        "|5        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________5|\n";
const string card6 =   " _________ \n"
                        "|6        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________6|\n";
const string card7 =   " _________ \n"
                        "|7        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________7|\n";
const string card8 =   " _________ \n"
                        "|8        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________8|\n";
const string card9 =   " _________ \n"
                        "|9        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________9|\n";
const string card10 =   " _________ \n"
                        "|10       |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|_______10|\n";
const string card11 =   " _________ \n"
                        "|Q        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________8|\n";
const string card12 =   " _________ \n"
                        "|J        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________J|\n";
const string card13 =   " _________ \n"
                        "|K        |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|         |\n"
                        "|________K|\n";
                        */
#endif